/*Full outer join left join + right join demektir.
  Karşılıkları olanları yazar iki tarafta karşılıkları olmayanları yazar karşılarına null yazar.
  outer gene opsiyonel
  */

--             DEPT1                             DEPT2
-- DEPARTMENT_ID | DEPARTMENT_NAME | DEPARTMENT_ID | DEPARTMENT_NAME

/*ANSI FORMAT*/
SELECT
    D1.DEPARTMENT_ID "Dept1 ID",
    D1.DEPARTMENT_NAME "Dept1 Name",
    D2.DEPARTMENT_ID "Dept2 ID",
    D2.DEPARTMENT_NAME "Dept Name",
    FROM DEPT1 D1
    FULL OUTER JOIN DEPT2 D2
    ON D1.DEPARTMENT_ID = D2.DEPARTMENT_ID
    ORDER BY 1;

/*GELENEKSEL FORMAT*/

/*INNER JOIN*/
SELECT
    D1.DEPARTMENT_ID "Dept1 ID",
    D1.DEPARTMENT_NAME "Dept1 Name",
    D2.DEPARTMENT_ID "Dept2 ID",
    D2.DEPARTMENT_NAME "Dept Name",
    FROM DEPT1 D1, DEPT2 D2
    WHERE D1.DEPARTMENT_ID = D2.DEPARTMENT_ID;

/*LEFT JOIN*/
SELECT
    D1.DEPARTMENT_ID "Dept1 ID",
    D1.DEPARTMENT_NAME "Dept1 Name",
    D2.DEPARTMENT_ID "Dept2 ID",
    D2.DEPARTMENT_NAME "Dept Name",
FROM DEPT1 D1, DEPT2 D2
WHERE D1.DEPARTMENT_ID = D2.DEPARTMENT_ID(+);

/*RIGHT JOIN*/
SELECT
    D1.DEPARTMENT_ID "Dept1 ID",
    D1.DEPARTMENT_NAME "Dept1 Name",
    D2.DEPARTMENT_ID "Dept2 ID",
    D2.DEPARTMENT_NAME "Dept Name",
FROM DEPT1 D1, DEPT2 D2
WHERE D1.DEPARTMENT_ID(+) = D2.DEPARTMENT_ID;

/*FULL JOIN LEFT + RİGHT Dİ UNION İLE BİRLEŞTİRİRSİN.*/
SELECT
    D1.DEPARTMENT_ID "Dept1 ID",
    D1.DEPARTMENT_NAME "Dept1 Name",
    D2.DEPARTMENT_ID "Dept2 ID",
    D2.DEPARTMENT_NAME "Dept Name",
FROM DEPT1 D1, DEPT2 D2
WHERE D1.DEPARTMENT_ID = D2.DEPARTMENT_ID(+);
UNION
SELECT
    D1.DEPARTMENT_ID "Dept1 ID",
    D1.DEPARTMENT_NAME "Dept1 Name",
    D2.DEPARTMENT_ID "Dept2 ID",
    D2.DEPARTMENT_NAME "Dept Name",
FROM DEPT1 D1, DEPT2 D2
WHERE D1.DEPARTMENT_ID(+) = D2.DEPARTMENT_ID;