/*SELF JOIN KENDI TABLOSUNA JOIN VERME İŞİDİR.*/
/*EMPLOYEE TABLOSUNDA BİR YONETICI ID Sİ TUTULUR YONETİCİ DE ASLINDA BİR ÇALIŞAN OLDUĞU İÇİN KENDİSİNE İŞARET EDER*/

FIRST_NAME | LAST_NAME | MANAGER_ID | MANAGER_NAME

/*GELENEKSEL FORMAT
    SELF JOIN + INNER JOIN OLDU
    */

SELECT
    E1.FIRST_NAME,
    E1.LAST_NAME,
    E1.MANAGER_ID,
    E2.FIRST_NAME,
    E2.LAST_NAME
    FROM EMPLOYEE E1, EMPLOYEE E2
WHERE E1.MANAGER_ID = E2.EMPLOYEE_ID
ORDER BY E1.EMPLOYEE_ID;

/*GELENEKSEL FORMAT
    SELF JOIN + LEFT JOIN OLDU
    */
SELECT
    E1.FIRST_NAME || '' || E1.LAST_NAME "Çalışan",
    E1.MANAGER_ID "Çalışanın Yönetici ID",
    E2.FIRST_NAME || '' || E2.LAST_NAME "Yöneticinin Adı"
FROM EMPLOYEE E1, EMPLOYEE E2
WHERE E1.MANAGER_ID = E2.EMPLOYEE_ID(+)
ORDER BY E1.EMPLOYEE_ID;


/*ANSI FORMAT*/
SELECT
        E1.FIRST_NAME || '' || E1.LAST_NAME "Çalışan",
        E1.MANAGER_ID "Çalışanın Yönetici ID",
        E2.FIRST_NAME || '' || E2.LAST_NAME "Yöneticinin Adı"
    FROM EMPLOYEES E1
    JOIN EMPLOYEES E2 ON E1.MANAGER_ID = E2.EMPLOYEE_ID;
-- SADECE JOIN YETERLİ SELF JOIN DE YAZABİLİRSİN İNNER JOİN YAPAR ASLINDA
-- LEFT JOIN VEYA RİGHT JOIN YAZARSAN SELF JOIN İÇİN LEFT RİGHT SAĞLAYABİLİRSİN.