/*
SIGN: Bir ifadenin foksiyonun işaretini bulur

ABS: Absolute yani mutlak değerini bulur.

COS,ACOS, COSH, SIN, ASIN, SINH, TAN, ATAN, TANH(A: ARC YANİ YERSİ DEMEK, H: HİPERBOLÜ DEMEK)

CEIL, FLOOR (ceil yukarıdaki en yakın tam sayıya, floor aşağı tam sayıya yuvarlar)

EXP, LN, LOG : Bunlar taban belirleyerek döner e üzeri ln üzer log üzeri

MOD: KALAN BULUR

POWER, SQRT: ÜSSÜ VE KAREKÖKÜNÜ VERİR

ROUND: YUVARLAMA FONKSİYONU

BURADAKİ TÜM FONKSİYONLAR SAYISAL DEĞER ALIR VE SAYISAL DEĞERLER DÖNER GERİYE
*/

/*ORACLE VERİTABANI KURULDUĞUNDA SANAL BİR TABLO OLAN DUAL DA HER ŞEMAYA KURULUR.*/

/************SIGN****************/
SELECT SIGN(-3), SIGN(3) FROM FROM DUAL;
/*-1 VE 1 DÖNER -1 NEGATİF 1 İSE POZİTİFDİR*/

SELECT SALARY, SIGN(SALARY) FROM EMPLOYEES;

/************ABS****************/
/*POZİTİFE ÇEVİRİR*/
SELECT ABS(-15), ABS(-100.12),ABS(123.45) FROM DUAL;

/*-1 , 4 VE 3 ÇIKTISI OLUR*/
SELECT SIGN(-3*15+1), ABS(-4 * 3 + 8), ABS(6-9) FROM DUAL;

/*STRİNG BİR PARAMETRE GEÇMEYE ÇALIŞIRSAN HATA ALIRSIN. SAYISAL FONKSİYONLAR SAYI PARAMETRESİ ALIR*/

/*İÇ İÇE KENDİSİNİ VEYA BAŞKA BİR FONKSİYONU ÇAĞIRABİLİRSİN SONUÇ OLARAK BU FONKSİYOLARDA BİR SAYI DÖNÜYOR*/
SELECT SIGN(-3 * 15 + 1 - ABS(-4*3+8)) FROM DUAL;

/************TRIGONOMETRİK FONKSİYONLAR****************/
/*GİRİLEN DEĞERLERİ RADYAN CİNSİNDEN ALDIĞI İÇİN ÇEVİRMEK GEREKİR
  pİ SAYISI İÇİN 22/7 VEYA AŞAĞIDAKİ İFADEYİ YAZABİLİRSİN. SONUÇ OLARAK KÖK 3 BÖLÜ 2 YERİNE SAYISAL DEĞERİNİ GÖSTERİR SANA
*/
SELECT COS(30 * 3.141592 / 180) FROM DUAL;
SELECT SIN(30 * (22/7) / 180) FROM DUAL;
SELECT COS(0) FROM DUAL;
SELECT SIN(0) FROM DUAL;
SELECT TAN(45 * (22/7) / 180) FROM DUAL;
/**/

SELECT ACOS(1), COS(0) FROM DUAL;

/*-1 VE 1 ARASINDA OLMALIDIR MATEMATİKSEL OLARAK*/
SELECT ACOS(5) FROM DUAL;

SELECT ACOS(1/2) FROM DUAL;

/***********************YUVARLAMA FONKSİYONları***********/

/*CEILT üst(tavan), floor(taban) alt tam sayıya yuvarlar.*/
/* 124 -5 123 -6*/
SELECT CEIL(123.456), CEIL(-5.6), FLOOR(123.456), FLOOR(-5.6) FROM DUAL;

/**********************ÜSTEL VE LOGARİTMA FONKSİYONLARI***********/
/*E ÜZERİ 1 2.78...*/
SELECT EXP(1), EXP(2) FROM DUAL;
SELECT LN(1), LN(2) FROM DUAL;
SELECT LOG(10,10), LOG(3,3), LOG(10,100) FROM DUAL;
/*Taban negatif olamaz.*/
SELECT LOG(-2,-5) FROM DUAL;
SELECT LOG(4,8) FROM DUAL;

/******************************MOD , POWER, SQRT*************************************/
SELECT MOD(5,2), MOD(97,5) FROM DUAL;

/*1 DEN 11 KADAR OLAN SAYILARI GÖSTERİR*/
SELECT LEVEL FROM DUAL CONNECT BY LEVEL < 12;

SELECT LEVEL, MOD(100,LEVEL) , MOD(23456, LEVEL) FROM DUAL CONNECT BY LEVEL < 12;

/*POWER KUVVETİNİ ALMAK İÇİNDİR*/
SELECT POWER(3,2) , POWER(2,3) FROM DUAL;
/*9 VE 8 BASAR*/

/*SQRT KAREKÖK*/
SELECT SQRT(25), SQRT(625) FROM DUAL;
/*5 25*/


