SELECT * FROM hr.DEPARTMENTS;

/*SELECT KULLANIRKEN HER HANGI BİR DEĞİŞKEN ÜZERİNE ATAMAMIZ GEREKIYOR INTO İLE*/

/*EXCEPTİON RUN TIME DA VERİLECEK YERLERİ YAKALAR EĞER SYNTAX DA HATA YAPTIYSAN ZATEN
  BU DERLEME AŞAMASINDA YAKALANIR VE ŞEMA DAKİ FUNCTIONS KISMINDA KIRMIZI GÖSTERİR.*/

/*İNTERRUP ETMEMEK İÇİN KODU EXCEPTİON YAZMAK LAZIM NAMED VEYA UNNAMED DA YAZABİLİRSİN EXCEPTİON KISMINI.*/


/*FONSİYONDA DEĞİŞİKLİK YAPTIĞINDA ŞEMA DA KAYITLI OLANI GÜNCELLEMEK İÇİN TEKRAR ÇALIŞTIRMAK LAZIM

  FUNCTION CREATED YAZDIĞINDA GÜNCELDİR.*/

CREATE OR REPLACE FUNCTION BOLUM_ADI(P_BOLUMNO IN NUMBER) RETURN VARCHAR2
    IS
WBOLUM_ADI VARCHAR2(30);
BEGIN
    SELECT DEPARTMENT_NAME INTO WBOLUM_ADI FROM hr.DEPARTMENTS WHERE DEPARTMENT_ID = P_BOLUMNO;

    RETURN (WBOLUM_ADI);

    EXCEPTION WHEN NO_DATA_FOUND THEN RETURN (P_BOLUMNO || ' NOLU BOLUM BULUNAMADI');
END;



DECLARE
    WADI VARCHAR2(30);
BEGIN
    WADI := BOLUM_ADI(10);
--     WADI := BOLUM_ADI(2); 2 OLMADIĞI İÇİN EXCEPTION A DÜŞÜCEK
    DBMS_OUTPUT.PUT_LINE(WADI);
end;



